tap "caskformula/caskformula"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "aria2"
brew "bash-completion"
brew "emacs", args: ["with-cocoa", "with-ctags", "with-librsvg", "with-modules"]
brew "fish"
brew "git"
brew "go"
brew "gradle"
brew "leiningen"
brew "openssl"
brew "sqlite"
brew "maven"
brew "p7zip"
brew "python"
brew "sbt"
brew "scala"
brew "telnet"
brew "the_silver_searcher"
brew "nvm"
# cask "haskell-platform"
